version: '3.7'

networks:
  shared: {}

services:
  db:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: the_world
      POSTGRES_DB: the_world_after
      POSTGRES_HOST_AUTH_METHOD: trust
    networks: [ 'shared' ]
    ports:
      - "5432:5432"
